erstellen von models (keine migrations), fluent Validation version update, TransactionService bug fix
angelos-nvg/Finance-Management-Lifesaver pull request #43
Opened 2023-11-14 15:43 UTC by Sikilacii

2023-11-14 15:46 UTC, angelos-nvg commented
Contact und Document Model raus

2023-11-14 15:47 UTC, Sikilacii commented
> Contact und Document Model raus

das wird danach gemacht
das ist ja unwichtig solange es keine errors macht und niemanden stört

2023-11-15 07:46 UTC, LHeidland reviewed
TLDR

2023-11-15 07:54 UTC, LHeidland requested changes
yyyyyyyyyyyyyyyyy so much??????

2023-11-15 08:35 UTC, angelos-nvg approved these changes

2023-11-15 08:46 UTC, closed without merging